name: Validate code

on: [push, pull_request]

jobs:
  code_quality:
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v2"
      
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      
      - name: Install dependencies
        run: pip install 'isort==5.*' black mypy pydocstyle
      
      - name: Change directory
        run: cd custom_components/rki_covid
      
      - name: isort
        run: isort --line-width 88 --trailing-comma -m 3 --check-only .
      
      - name: black
        run: black --check .
      
      - name: pydocstyle
        run: pydocstyle .
      
      - name: mypy
        run: mypy --ignore-missing-imports --follow-imports=silent custom_components/rki_covid
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: Download repo
      - uses: actions/setup-python@v2
        name: Setup Python
      - uses: actions/cache@v2
        name: Cache
        with:
          path: |
            ~/.cache/pip
          key: custom-component-ci
      - uses: hacs/action@main
        with:
          CATEGORY: integration
      - uses: KTibow/ha-blueprint@stable
        name: CI
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          FORMAT_CODE: DISABLED
          FLAKE8_FAILS: E9,F63,F7,F82,S
